Feat: Vault list reorder
vultisig/vultisig-android pull request #137
Opened 2024-05-20 00:44 UTC by aminsato

2024-05-20 05:37 UTC, YGolybev commented on app/src/main/java/com/vultisig/wallet/presenter/home/HomeViewModel.kt
> +            vaultDB.selectAll()
As in [previous PR](https://github.com/vultisig/vultisig-android/pull/134#discussion_r1605977378), the update's lambda can be reevaluated more than once, so consider moving calculations out of it.

2024-05-20 10:35 UTC, YGolybev commented on app/src/main/java/com/vultisig/wallet/presenter/home/HomeViewModel.kt
> +            vaultDB.selectAll()
Also, if you don't care for the current value of state flow, using `Stateflow.value = value` may be a bit more optimal

2024-05-21 06:10 UTC, YGolybev requested changes

2024-05-21 06:10 UTC, yvebe commented on app/src/main/java/com/vultisig/wallet/presenter/home/HomeViewModel.kt
> +    var vaults = MutableStateFlow<List<Vault>> (emptyList())
```suggestion
    val vaults = MutableStateFlow<List<Vault>> (emptyList())
```

2024-05-21 06:10 UTC, yvebe commented on app/src/main/java/com/vultisig/wallet/presenter/home/HomeViewModel.kt
> +        }
```suggestion
        vaults.value = vaultDB.selectAll()
```

2024-05-21 06:10 UTC, yvebe commented on app/src/main/java/com/vultisig/wallet/presenter/home/HomeViewModel.kt
> +        }
Why is this required? Also, using delay is a sign that something is most likely wrong.

2024-05-21 06:10 UTC, yvebe commented on app/src/main/java/com/vultisig/wallet/presenter/home/VaultCeil.kt
> +            Icon(painter = painterResource(id = R.drawable.hamburger_menu), contentDescription = "draggable item",modifier = Modifier.width(16.dp))
Please stay under Android Studio's characters per line limit (100 characters)

2024-05-21 06:10 UTC, yvebe commented on app/src/main/java/com/vultisig/wallet/data/on_board/db/VaultDB.kt
> +        }.reversed()
Please store vaults and their sorting order on different tables (in other JSON files). Imagine what would be if we had vaults with different sorting orders on different screens (we would need too many fields in the vault). 
Also, please try to keep updating the vault index using a single method. Later on, we will use something like an integer position column, which can work in a single transaction. 

[Check out this article](https://begriffs.com/posts/2018-03-20-user-defined-order.html)

2024-05-21 09:08 UTC, aminsato commented on app/src/main/java/com/vultisig/wallet/presenter/home/HomeViewModel.kt
> +        }
onmove method invoked repeatedly per each position changing. so if the current position is 0 and it moved to position 2, onMove method called 2 times. so for preventing database update during item movement i cancel the job of reIndexing until the movement action finished and wait for 500ms and then reIndex the data.

2024-05-22 03:45 UTC, aminsato commented on app/src/main/java/com/vultisig/wallet/data/on_board/db/VaultDB.kt
> +        }.reversed()
Done

2024-05-22 05:14 UTC, YGolybev approved these changes

2024-05-22 07:58 UTC, merged