Update camera denied permission ui
vultisig/vultisig-android pull request #208
Opened 2024-05-24 09:00 UTC by aminsato

2024-05-24 09:47 UTC, YGolybev requested changes

2024-05-24 09:47 UTC, YGolybev commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                        ),
Please, refrain from using dimens; they're breaking the layout. Just specify values from Figma.

2024-05-24 09:47 UTC, YGolybev commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                    textStyle = Theme.montserrat.titleLarge,
Please refrain from using Material aliases for our fonts; that's just misleading

2024-05-24 09:47 UTC, YGolybev commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                        )
Please, specify image size

2024-05-24 09:47 UTC, YGolybev commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                            style = Theme.montserrat.titleMedium,
It's menlo.subtitle1 in Figma

2024-05-24 19:18 UTC, aminsato commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                        ),
Doine

2024-05-24 19:19 UTC, aminsato commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                            style = Theme.montserrat.titleMedium,
Done, please check again

2024-05-24 19:19 UTC, aminsato commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                        )
Done

2024-05-24 19:19 UTC, aminsato commented on app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
> +                    textStyle = Theme.montserrat.titleLarge,
Done

2024-05-25 07:09 UTC, YGolybev approved these changes

2024-05-25 09:33 UTC, merged